services:
  app:
    image: my-app:latest
    pull_policy: never
    container_name: myapp_container
    env_file:
      - .docker.env
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - appdata:/app
  db:
    image: postgres:16
    container_name: db
    restart: always
    env_file:
      - .docker.env
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
  appdata:
