-- sb-pull: realtime and rls start
-- Auto-generated by scripts/supabase/sb-pull.ts
-- This block is source-controlled so CI gets realtime + RLS changes.
ALTER PUBLICATION supabase_realtime OWNER TO postgres;
ALTER PUBLICATION supabase_realtime ADD TABLE ONLY core.account_notification;
ALTER PUBLICATION supabase_realtime ADD TABLE ONLY core.admin;
ALTER PUBLICATION supabase_realtime ADD TABLE ONLY core.profile;
ALTER PUBLICATION supabase_realtime ADD TABLE ONLY core.role;
ALTER PUBLICATION supabase_realtime ADD TABLE ONLY core.role_account;
ALTER PUBLICATION supabase_realtime ADD TABLE ONLY core.session;
ALTER PUBLICATION supabase_realtime ADD TABLE ONLY test.test;
ALTER TABLE core.account_notification ENABLE ROW LEVEL SECURITY;
ALTER TABLE core.admin ENABLE ROW LEVEL SECURITY;
ALTER TABLE core.profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE core.role ENABLE ROW LEVEL SECURITY;
ALTER TABLE core.role_account ENABLE ROW LEVEL SECURITY;
ALTER TABLE core.session ENABLE ROW LEVEL SECURITY;
ALTER TABLE public._template ENABLE ROW LEVEL SECURITY;
ALTER TABLE realtime.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE test.test ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all to all" ON test.test USING (true) WITH CHECK (true);
-- sb-pull: realtime and rls end
