import { config } from '../src/lib/server/utils/env';
import fs from 'fs';

export default async () => {
	return fs.writeFileSync(
		'src/lib/types/supabase-schema.ts',
		`
/* 
This file is generated by the supabase-init script. Do not edit this file directly. If you need to change the schema name, edit the config in src/lib/server/utils/env.ts and run pnpm sb:init again.
This file is also gitignored, so it won't be committed to version control.
*/
        
export type SchemaName = '${config.supabase.schema}';
export const schemaName: SchemaName = '${config.supabase.schema}';
`.trim()
	);
};
