
  create table "core"."session_tab" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "archived" boolean not null default false,
    "session_id" uuid not null,
    "url" text not null
      );


alter table "core"."session_tab" enable row level security;

CREATE UNIQUE INDEX session_tab_pkey ON core.session_tab USING btree (id);

alter table "core"."session_tab" add constraint "session_tab_pkey" PRIMARY KEY using index "session_tab_pkey";

alter table "core"."session_tab" add constraint "session_tab_session_id_fkey" FOREIGN KEY (session_id) REFERENCES core.session(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "core"."session_tab" validate constraint "session_tab_session_id_fkey";

grant delete on table "core"."session_tab" to "anon";

grant insert on table "core"."session_tab" to "anon";

grant references on table "core"."session_tab" to "anon";

grant select on table "core"."session_tab" to "anon";

grant trigger on table "core"."session_tab" to "anon";

grant truncate on table "core"."session_tab" to "anon";

grant update on table "core"."session_tab" to "anon";

grant delete on table "core"."session_tab" to "authenticated";

grant insert on table "core"."session_tab" to "authenticated";

grant references on table "core"."session_tab" to "authenticated";

grant select on table "core"."session_tab" to "authenticated";

grant trigger on table "core"."session_tab" to "authenticated";

grant truncate on table "core"."session_tab" to "authenticated";

grant update on table "core"."session_tab" to "authenticated";

grant delete on table "core"."session_tab" to "service_role";

grant insert on table "core"."session_tab" to "service_role";

grant references on table "core"."session_tab" to "service_role";

grant select on table "core"."session_tab" to "service_role";

grant trigger on table "core"."session_tab" to "service_role";

grant truncate on table "core"."session_tab" to "service_role";

grant update on table "core"."session_tab" to "service_role";


  create table "test"."join_test" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "archived" boolean not null default false,
    "test_id" uuid
      );


alter table "test"."join_test" enable row level security;

CREATE UNIQUE INDEX join_test_pkey ON test.join_test USING btree (id);

alter table "test"."join_test" add constraint "join_test_pkey" PRIMARY KEY using index "join_test_pkey";

alter table "test"."join_test" add constraint "join_test_test_id_fkey" FOREIGN KEY (test_id) REFERENCES test.test(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "test"."join_test" validate constraint "join_test_test_id_fkey";

grant delete on table "test"."join_test" to "anon";

grant insert on table "test"."join_test" to "anon";

grant select on table "test"."join_test" to "anon";

grant update on table "test"."join_test" to "anon";

grant delete on table "test"."join_test" to "authenticated";

grant insert on table "test"."join_test" to "authenticated";

grant references on table "test"."join_test" to "authenticated";

grant select on table "test"."join_test" to "authenticated";

grant trigger on table "test"."join_test" to "authenticated";

grant truncate on table "test"."join_test" to "authenticated";

grant update on table "test"."join_test" to "authenticated";

grant delete on table "test"."join_test" to "service_role";

grant insert on table "test"."join_test" to "service_role";

grant references on table "test"."join_test" to "service_role";

grant select on table "test"."join_test" to "service_role";

grant trigger on table "test"."join_test" to "service_role";

grant truncate on table "test"."join_test" to "service_role";

grant update on table "test"."join_test" to "service_role";


  create policy "All can do all"
  on "test"."join_test"
  as permissive
  for all
  to public
using (true)
with check (true);



