/* 
This file is generated by the supabase-init script. Do not edit this file directly. If you need to change the schema name, edit the config in src/lib/server/utils/env.ts and run pnpm sb:init again.
This file is also gitignored, so it won't be committed to version control.
*/

export type SchemaName = 'sveltekit_template';
export const schemaName: SchemaName = 'sveltekit_template';
