/* 
This file is generated by the supabase-gen script. Do not edit this file directly.
*/

import { z } from "zod";

export const schemas = {
  account_notification: {
    Row: z.object({ account_id: z.string().nullable(), archived: z.boolean(), created_at: z.string(), icon: z.string(), icon_type: z.string(), id: z.string(), link: z.string().nullable(), message: z.string(), read: z.boolean(), severity: z.string(), title: z.string() }),
    Insert: z.object({ account_id: z.string().nullable().optional(), archived: z.boolean(), created_at: z.string().optional(), icon: z.string(), icon_type: z.string(), id: z.string().optional(), link: z.string().nullable().optional(), message: z.string(), read: z.boolean().optional(), severity: z.string(), title: z.string() }),
    Update: z.object({ account_id: z.string().nullable().optional(), archived: z.boolean().optional(), created_at: z.string().optional(), icon: z.string().optional(), icon_type: z.string().optional(), id: z.string().optional(), link: z.string().nullable().optional(), message: z.string().optional(), read: z.boolean().optional(), severity: z.string().optional(), title: z.string().optional() }),
  },
  admin: {
    Row: z.object({ archived: z.boolean(), created_at: z.string(), id: z.string() }),
    Insert: z.object({ archived: z.boolean().optional(), created_at: z.string().optional(), id: z.string().optional() }),
    Update: z.object({ archived: z.boolean().optional(), created_at: z.string().optional(), id: z.string().optional() }),
  },
  profile: {
    Row: z.object({ archived: z.boolean(), email: z.string(), first_name: z.string(), id: z.string(), last_name: z.string(), username: z.string() }),
    Insert: z.object({ archived: z.boolean().optional(), email: z.string().optional(), first_name: z.string(), id: z.string().optional(), last_name: z.string(), username: z.string() }),
    Update: z.object({ archived: z.boolean().optional(), email: z.string().optional(), first_name: z.string().optional(), id: z.string().optional(), last_name: z.string().optional(), username: z.string().optional() }),
  },
  role: {
    Row: z.object({ archived: z.boolean(), color: z.string().nullable(), created_at: z.string(), description: z.string().nullable(), id: z.string(), name: z.string(), parent: z.string().nullable() }),
    Insert: z.object({ archived: z.boolean().optional(), color: z.string().nullable().optional(), created_at: z.string().optional(), description: z.string().nullable().optional(), id: z.string().optional(), name: z.string(), parent: z.string().nullable().optional() }),
    Update: z.object({ archived: z.boolean().optional(), color: z.string().nullable().optional(), created_at: z.string().optional(), description: z.string().nullable().optional(), id: z.string().optional(), name: z.string().optional(), parent: z.string().nullable().optional() }),
  },
  role_account: {
    Row: z.object({ account_id: z.string(), archived: z.boolean().nullable(), id: z.string(), role_id: z.number() }),
    Insert: z.object({ account_id: z.string(), archived: z.boolean().nullable().optional(), id: z.string().optional(), role_id: z.number() }),
    Update: z.object({ account_id: z.string().optional(), archived: z.boolean().nullable().optional(), id: z.string().optional(), role_id: z.number().optional() }),
  },
  session: {
    Row: z.object({ account_id: z.string().nullable(), archived: z.boolean(), created_at: z.string(), id: z.string(), prev_url: z.string().nullable() }),
    Insert: z.object({ account_id: z.string().nullable().optional(), archived: z.boolean().optional(), created_at: z.string().optional(), id: z.string().optional(), prev_url: z.string().nullable().optional() }),
    Update: z.object({ account_id: z.string().nullable().optional(), archived: z.boolean().optional(), created_at: z.string().optional(), id: z.string().optional(), prev_url: z.string().nullable().optional() }),
  },
  test: {
    Row: z.object({ age: z.number(), archived: z.boolean().nullable(), created_at: z.string(), id: z.string(), name: z.string() }),
    Insert: z.object({ age: z.number(), archived: z.boolean().nullable().optional(), created_at: z.string().optional(), id: z.string().optional(), name: z.string() }),
    Update: z.object({ age: z.number().optional(), archived: z.boolean().nullable().optional(), created_at: z.string().optional(), id: z.string().optional(), name: z.string().optional() }),
  }
} as const;
