/* 
This file is generated by the supabase-gen script. Do not edit this file directly.
*/

import { z } from "zod";

export const schemas = {
  test: {
    Row: z.object({ created_at: z.string(), id: z.string() }),
    Insert: z.object({ created_at: z.string().optional(), id: z.string().optional() }),
    Update: z.object({ created_at: z.string().optional(), id: z.string().optional() }),
  }
} as const;
