name: 'Merge Template'

on:
  release:
    types: [published]

jobs:
  pre-check:
    runs-on: ubuntu-latest
    outputs:
      run_pipeline: ${{ steps.check.outputs.run_pipeline }}
    steps:
      - id: check
        run: |
          if [[ "${{ github.event.release.name }}" == *deploy* ]]; then
            echo "run_pipeline=true" >> $GITHUB_OUTPUT
          else
            echo "run_pipeline=false" >> $GITHUB_OUTPUT
          fi
  format:
    needs: pre-check
    if: needs.pre-check.outputs.run_pipeline == 'true'
    uses: ./.github/workflows/code-formatter.yml
  unit-tests:
    needs: pre-check
    if: needs.pre-check.outputs.run_pipeline == 'true'
    uses: ./.github/workflows/testing-unit.yml
  E2E:
    needs: pre-check
    if: needs.pre-check.outputs.run_pipeline == 'true'
    uses: ./.github/workflows/testing-e2e.yml
  check:
    needs: pre-check
    if: needs.pre-check.outputs.run_pipeline == 'true'
    uses: ./.github/workflows/testing-svelte-check.yml
  docker-compose:
    needs: pre-check
    if: needs.pre-check.outputs.run_pipeline == 'true'
    uses: ./.github/workflows/docker-compose-test.yml

  push-docker-image:
    runs-on: ubuntu-latest
    needs: [format, unit-tests, E2E, check, docker-compose]
    steps:
      - name: Log in to Gitea Registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ${{ secrets.GITEA_REGISTRY_URL }}
          username: ${{ secrets.GITEA_REGISTRY_USER }}
          password: ${{ secrets.GITEA_REGISTRY_PWD }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Retrieve credentials and push image
        run: |
          TAG=${{ github.event.release.tag_name }}
          REPOSITORY=$(basename $GITHUB_REPOSITORY)

          docker build -t ${{ secrets.GITEA_REGISTRY_URL }}/${{ secrets.GITEA_REGISTRY_USER }}/$REPOSITORY:${TAG} -t ${{ secrets.GITEA_REGISTRY_URL }}/${{ secrets.GITEA_REGISTRY_USER }}/$REPOSITORY:latest .

          docker push ${{ secrets.GITEA_REGISTRY_URL }}/${{ secrets.GITEA_REGISTRY_USER }}/$REPOSITORY:${TAG}
          docker push ${{ secrets.GITEA_REGISTRY_URL }}/${{ secrets.GITEA_REGISTRY_USER }}/$REPOSITORY:latest
