name: e2e

on:
  workflow_call:
    # secrets:
    #   GH_TOKEN:
    #     description: 'GitHub Token'
    #     required: true
  push:
    branches:
      - '*'
      - '!deploy'
      - '!gh-pages'

permissions:
  contents: read

jobs:
  e2e-tests:
    # this has a chance of infinite loop if we write a test wrong, timeout should catch it eventually.
    timeout-minutes: 5
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Load .env variables
        run: |
          cp config.example.json config.json
          touch .env
          echo "OAUTH2_CLIENT_ID=1234567890" >> .env
          echo "OAUTH2_CLIENT_SECRET=1234567890" >> .env
          echo "CONFIG_PATH=./config.json" >> .env
          export $(cat .env | xargs)
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pnpm add -D typescript
          pnpm install --frozen-lockfile
          pnpm exec playwright install

      - name: Set up Supabase Config
        run: |
          echo "Setting up Supabase config..."
          COMMIT_HASH=$(git rev-parse --short HEAD)
          SCHEMA_NAME="unit_test_${COMMIT_HASH}"
          sed -i "s/^project_id = .*/project_id = \"${SCHEMA_NAME}\"/" supabase/config.toml
          pnpm sb:start --debug
          pnpm run sb:local-config
          pnpm run sb:set-schema ${SCHEMA_NAME}
          pnpm run sb:push

      - name: Init supabase types
        run: |
          pnpm run sb:init
          pnpm run sb:set-schema +=e2e_testing

      - name: Run
        run: |
          echo "Running e2e tests..."
          pnpm run test:e2e

      - name: Shutdown supabase
        if: always()
        run: pnpm sb:stop --no-backup

      - name: Clean up Supabase config
        if: always()
        run: rm -f config.json .env
