name: Svelte Check

on:
  workflow_call:
    # secrets:
    #   GH_TOKEN:
    #     description: 'GitHub Token'
    #     required: true
  push:
    branches:
      - '*'
      - '!deploy'
      - '!gh-pages'

permissions:
  contents: read

jobs:
  tsc:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Retrieve git dependencies
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          #  token: ${{ secrets.GH_TOKEN }}

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pnpm add -D typescript
          pnpm install --frozen-lockfile

      - name: Load .env variables
        run: |
          cp config.example.json config.json
          touch .env
          echo "OAUTH2_CLIENT_ID=1234567890" >> .env
          echo "OAUTH2_CLIENT_SECRET=1234567890" >> .env
          echo "CONFIG_PATH=./config.json" >> .env
          export $(cat .env | xargs)
      - name: Set up Supabase Config
        run: |
          echo "Setting up Supabase config..."
          COMMIT_HASH=$(git rev-parse --short HEAD)
          SCHEMA_NAME="check_${COMMIT_HASH}"
          pnpm run sb:config schema_name=${SCHEMA_NAME} tenant_id=${{ secrets.SB_TENANT_ID }} pg_pass=${{ secrets.SB_PG_PASS }} anon_key=${{ secrets.SB_ANON_KEY }} domain=${{ secrets.SB_DOMAIN }} service_role_key=${{ secrets.SB_SERVICE_ROLE_KEY }} sb_pass=${{ secrets.SB_SB_PASS }} local_ip=${{ secrets.SB_LOCAL_IP }} --force
          pnpm run sb:set-schema ${SCHEMA_NAME}
          pnpm run sb:push

      - name: Init supabase types
        run: pnpm run sb:init

      - name: Run
        run: |
          echo "Testing..."
          pnpm run check

      - name: Drop Supabase schema
        if: always()
        run: pnpm run sb:drop-schema

      - name: Clean up Supabase config
        if: always()
        run: rm -f config.json .env
