name: Unit Tests

on:
  workflow_call:
    # secrets:
    #   GH_TOKEN:
    #     description: 'GitHub Token'
    #     required: true
  push:
    branches:
      - '*'
      - '!deploy'
      - '!gh-pages'

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pnpm add -D typescript
          pnpm install --frozen-lockfile

      - name: Load .env variables
        run: |
          cp config.example.json config.json
          touch .env
          echo "OAUTH2_CLIENT_ID=1234567890" >> .env
          echo "OAUTH2_CLIENT_SECRET=1234567890" >> .env
          echo "CONFIG_PATH=./config.json" >> .env
          export $(cat .env | xargs)
      - name: Set up Supabase Config
        run: |
          echo "Setting up Supabase config..."
          COMMIT_HASH=$(git rev-parse --short HEAD)
          SCHEMA_NAME="unit_test_${COMMIT_HASH}"
          pnpm run sb:config pg_pass=postgres public_key=${{ secrets.SB_PUBLIC_KEY }} domain=127.0.0.1 secret_key=${{ secrets.SB_SECRET_KEY }} local_ip=127.0.0.1 --force
          pnpm run sb:set-schema ${SCHEMA_NAME}
          pnpm run sb:push

      - name: Init supabase types
        run: pnpm run sb:init

      - name: Run Vitest tests
        run: npm run test:unit

      - name: Drop Supabase schema
        if: always()
        run: pnpm run sb:drop-schema

      - name: Clean up Supabase config
        if: always()
        run: rm -f config.json .env
